Repository deliverycenter/dc.libs.metrics.ruby, pull requests merged in 2020-11, with the labels that each got.

#1 Initial setup of the repo as a ruby gem
  .gitignore
  .rspec
  Gemfile
  Gemfile.lock
  LICENSE.txt
  README.md
  Rakefile
  bin/console
  bin/setup
  dc-metrics.gemspec
  lib/dc/metrics.rb
  lib/dc/metrics/version.rb
  spec/dc/metrics_spec.rb
  spec/spec_helper.rb
Labels: documentation, enhancement

#2 Update gemspec
  .gitignore
  README.md
  dc-metrics.gemspec
Labels: documentation

#3 Add configuration block for gem parameters
  README.md
  lib/dc/metrics.rb
  lib/dc/metrics/configuration.rb
  spec/spec_helper.rb
Labels: documentation, enhancement

#4 Feature/create lib interface and initial workings
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
  Rakefile
  bin/console
  dc-metrics.gemspec
  lib/dc/metrics.rb
  lib/dc/metrics/configuration.rb
  lib/dc/metrics/logger.rb
  lib/dc/metrics/version.rb
  lib/protos/metrics_pb.rb
  spec/dc/metrics/logger_spec.rb
  spec/dc/metrics_spec.rb
  spec/spec_helper.rb
Labels: documentation, enhancement

#5 Add pub sub publication
  Gemfile.lock
  README.md
  bin/console
  dc-metrics.gemspec
  lib/dc/metrics.rb
  lib/dc/metrics/configuration.rb
  lib/dc/metrics/logger.rb
  lib/dc/metrics/pub_sub.rb
Labels: enhancement

#6 [PB-393] Disable metrics behavior
  README.md
  lib/dc/metrics.rb
  lib/dc/metrics/configuration.rb
  lib/dc/metrics/logger.rb
Labels: enhancement

#8 Allow gem push to rubygems org
  dc-metrics.gemspec
  lib/dc/metrics/version.rb
Labels: enhancement
